### ISSUE TITLE
Any plans for .NET Core support?

### ISSUE THREAD

**Issue by mtttcgcg** [SummerBatch/SummerBatch#11]
We like this framework but are moving towards .NET Core. Is there any plan to port (might necessitate a Unity replacement with something like Autofac since I don't think Unity supports .NET Core yet either).

**Comment by askids** [comment]
I think that one of the original reasons mentioned for not supporting .NET Core was lack of support for transactions. That should be resolved with v2.0. So I am assuming that any support for .NET Core, if and when available, will be based on .NET Core 2.0. Is that correct?

**Comment by SummerBatchTeam** [comment]
Hi, we are currently working on a .Net core version for SummerBatch. Work is in progress. The first version is planned for Q1 2018. You're right the main subjects are replacement of Unity and connections/transactions.

**Comment by hanswieheiri** [comment]
Looks like an interesting project. Is .NET Core support still on your roadmap? Thanks a lot

**Comment by randy-torres** [comment]
Hi! Any update on the .NET Core version?

**Comment by SummerBatchTeam** [comment]
Hi,
Due to some technical limitations on the injection framework available in the .Net Core, the migration has been postponed. SummerBatch core design requires some advanced features and customizations that are not available in any .Net Core injection framework. Migration will re-examined at a later date.
